version: '3.8'
services:
  app:
    build:
      context: ./app
    ports:
      - "4000:4000"
    networks:
      - app-network
    volumes:
      - ./app:/app
    command: ["npm", "run", "dev"]

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - app-network

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./client:/client
    command: ["npm", "run", "dev"]

networks:
  app-network:
    driver: bridge